version: '3.8'
services:

  stats-server:
    build: ./stat/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - db-stat
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-stat:5432/db-stat
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  db-stat:
    image: postgres:14-alpine
    container_name: db-stat
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=db-stat
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm


  ewm-service:
    build: ./ewm-service/
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - db-ewm-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-ewm-service:5434/db-ewm-service
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  db-ewm-service:
    image: postgres:14-alpine
    container_name: db-ewm-service
    ports:
      - "6543:5434"
    environment:
      - POSTGRES_DB=db-ewm-service
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    command: -p 5434